=== Kissaki/MKVToolNix/examples/matroskachapters.dtd
<!ENTITY % format "(ascii|base64|hex)">
<!ELEMENT Chapters (EditionEntry*)>
<!ELEMENT EditionEntry (
          EditionUID?,
          EditionFlagHidden?,
          EditionFlagOrdered?,
          EditionFlagDefault?,
          EditionDisplay*,
          ChapterAtom*)>

<!ELEMENT EditionUID (#PCDATA)>
<!ELEMENT EditionFlagHidden (#PCDATA)>
<!ELEMENT EditionFlagOrdered (#PCDATA)>
<!ELEMENT EditionFlagDefault (#PCDATA)>
<!ELEMENT EditionString (#PCDATA)>
<!ELEMENT EditionLanguageIETF (#PCDATA)>

<!ELEMENT EditionDisplay (
          EditionString,
          EditionLanguageIETF* )>

<!ELEMENT ChapterAtom (
          ChapterTimeStart,
          ChapterTimeEnd?,
          ChapterUID?,
          ChapterSegmentUID?,
          ChapterSegmentEditionUID?,
          ChapterPhysicalEquiv?,
          ChapterTrack?,
          ChapterFlagHidden?,
          ChapterFlagEnabled?,
          ChapterDisplay*,
          ChapterProcess*,
          ChapterSkipType?,
          ChapterAtom*)>

<!ELEMENT ChapterTrack (ChapterTrackNumber)>
<!ELEMENT ChapterTrackNumber (#PCDATA)>

<!ELEMENT ChapterDisplay (
          ChapterString,
          ChapterLanguage*,
          ChapLanguageIETF*,
          ChapterCountry*)>

<!ELEMENT ChapterProcess (
          ChapterProcessCodecID,
          ChapterProcessPrivate?,
          ChapterProcessCommand+)>

<!ELEMENT ChapterProcessCommand (
          ChapterProcessTime,
          ChapterProcessData)>

<!ELEMENT ChapterTimeStart (#PCDATA)>
<!ELEMENT ChapterTimeEnd (#PCDATA)>
<!ELEMENT ChapterFlagHidden (#PCDATA)>
<!ELEMENT ChapterFlagEnabled (#PCDATA)>
<!ELEMENT ChapterUID (#PCDATA)>
<!ELEMENT ChapterSkipType (#PCDATA)>

<!ELEMENT ChapterSegmentUID (#PCDATA)>
<!ATTLIST ChapterSegmentUID format %format; "ascii">
<!ELEMENT ChapterSegmentEditionUID (#PCDATA)>
<!ELEMENT ChapterPhysicalEquiv (#PCDATA)>

<!ELEMENT ChapterProcessCodecID (#PCDATA)>
<!ELEMENT ChapterProcessPrivate (#PCDATA)>
<!ATTLIST ChapterProcessPrivate format %format; "ascii">
<!ELEMENT ChapterProcessTime (#PCDATA)>
<!ELEMENT ChapterProcessData (#PCDATA)>
<!ATTLIST ChapterProcessData format %format; "ascii">

<!ELEMENT ChapterString (#PCDATA)>
<!ELEMENT ChapterLanguage (#PCDATA)>
<!ELEMENT ChapLanguageIETF (#PCDATA)>
<!ELEMENT ChapterCountry (#PCDATA)>

=== Kissaki/MKVToolNix/examples/example-chapters-1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE Chapters SYSTEM "matroskachapters.dtd">

<!-- A simple example. The movie in question contains four parts: -->
<!-- The intro starting at the beginning, the first act, the second -->
<!-- act, and the credits. -->

<!-- Note that the end timestamps are optional. -->

<!-- The timestamps use the normal format of HH:MM:SS.mmm with -->
<!-- HH beging the hour, MM the minute, SS the second and -->
<!-- mmm the milliseconds. -->

<Chapters>
  <EditionEntry>
    <EditionDisplay>
      <EditionString>Example movie</EditionString>
      <EditionLanguageIETF>en</EditionLanguageIETF>
    </EditionDisplay>
    <ChapterAtom>
      <ChapterTimeStart>00:00:00.000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Intro</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
      <ChapterSkipType>1</ChapterSkipType>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterTimeStart>00:01:00.000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Act 1</ChapterString>
        <ChapLanguageIETF>en</ChapLanguageIETF>
      </ChapterDisplay>
      <ChapterSkipType>0</ChapterSkipType>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterTimeStart>00:05:30.000</ChapterTimeStart>
      <ChapterDisplay>
        <ChapterString>Act 2</ChapterString>
        <ChapLanguageIETF>en</ChapLanguageIETF>
      </ChapterDisplay>
      <ChapterSkipType>0</ChapterSkipType>
    </ChapterAtom>
    <ChapterAtom>
      <ChapterTimeStart>00:12:20.000</ChapterTimeStart>
      <ChapterTimeEnd>00:12:55.000</ChapterTimeEnd>
      <ChapterDisplay>
        <ChapterString>Credits</ChapterString>
        <ChapLanguageIETF>en</ChapLanguageIETF>
      </ChapterDisplay>
      <ChapterSkipType>2</ChapterSkipType>
    </ChapterAtom>
  </EditionEntry>

  <!-- There are two new flags that have been added to Matroska lately. -->
  <!-- They are flags that enable/disable and hide/unhide chapters. -->
  <!-- Here's just a small example: -->
  <EditionEntry>
    <ChapterAtom>
      <ChapterTimeStart>00:02:00.000</ChapterTimeStart>
      <ChapterTimeEnd>00:04:00.000</ChapterTimeEnd>
      <ChapterFlagHidden>1</ChapterFlagHidden>
      <ChapterFlagEnabled>0</ChapterFlagEnabled>
      <ChapterDisplay>
        <ChapterString>A hidden and not enabled chapter.</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
    </ChapterAtom>
  </EditionEntry>
</Chapters>
